# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f938867803e202dc218f470f58ad7b08b9826d1f881b7552c5874575d330f7f1633f4b22da3cd848247dd80dfb9e359a69e903d376cf82b35088b4699b0bf38

test:
  secret_key_base: dccf5ce1e81a908180df3e10a522a165c70d6ec92d64bafae9a4499c928e5def665536985a7c83a91cffb81f815b77c7485138afe2e379529990a085504a2eb1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
